### ISSUE TITLE
Forum Expansion

### ISSUE THREAD

**Issue by IsoPhoenix** [hcs-t4sg/questable#64]
## Overview
Expanding forum functionality based on feedback from midpoint. Details/suggestions organized per feature below.

### Edit/Delete forum post
* Teachers should be able to delete any forum posts or comments.
* By a toggleable option (on by default) in the teacher's settings, students should be able to edit/delete their own posts (note, not comments)
	* *I'm suggesting this distinction because students could potentially be malicious with editing/deleting posts? Such as editing posts after receiving the answer to troll. Editing/deleting posts could be helpful if a student needs to correct a mistake they made in the post. Comments don't need to be edited as sending another message shouldn't be too difficult, also this mirrors native iMessage functionality.*

### Anonymous forum posts
* Students should have the option to make a post anonymously (no identifying information associated). We can leave comments as-is (always identifying)

### Like posts, like/pin comments
* Ability for anyone to like a post
	* To keep track of likes, it's probably easiest to store an array field `playerLikes` with each post document containing the user/player IDs of players who have liked that post. Firestore has helpful `arrayContains` and `arrayUnion` methods that can manage this list and keep players from liking multiple times.
* Ability for anyone to like a comment (see above)
* Ability for teacher or the original poster to "star"/"pin" comments that they find helpful. These comments would be listed in a section below the original post content but above the chatbox (do not remove the comments from the chatbox)

### Search posts by title
Self-explanatory

### Multiline forum posts and/or editor integration
Preserve line breaks/enters in original post content. Alternatively, you could look around and see if there are any packages that will integrate rich text editors into a React webapp, which would give us multiline support, bold/italicize, maybe even code blocks/markdown/LaTEX (although a bit of a stretch)...

**Comment by jaydenpersonnat** [comment]
Implemented functionality for editing/deleting, anonymity, and liking, though I had a few questions: 

1. For `forumPost`, should anonymity be an editable field for students, or should we keep it as something that a student selects once when creating the post? I also did not give teachers the ability to affect the anonymity of the point. 

2. Under my current implementation, posts are made anonymously in the sense that I have added an `anonymous` field where a student's information is hidden from a post if `anonymous = 1` to all the players in the classroom. Or, should I not even store any student's information when an anonymous post is made? Right now, the student who made the post anonymously and the teacher can edit and delete the post (when the option is on). With the latter implementation, only the teacher would be able to remove an anonymous post. 

3. In terms of pin/starred comments, how should it look design-wise? Should pin comments go in a container similar to the one used for comments and the post content? 

4. For searching, are there any Figma designs on what it should look like? Should search be implemented such that the posts currently displayed in the FormView change in place, or should I create some kind of modal/results page that shows the search results? 

5. Any particular preference on a text editor? Popular ones seem to be Draft.js, Quill, TipTap, and Prose Mirror.

**Comment by IsoPhoenix** [comment]
1. Let's just keep it non-editable, I think that's simpler and better UX!
2. I think your current implementation is good!
3. Yeah that sounds good, put them in a MUI card similar to the post content and chatbot currently. You can probably reuse/modify the component for a message bubble to display pinned/starred comments. Ed has a checkmark and endorse feature for student vs. teacher pinning, but I would just keep it as "pinned" for now and add a small annotation for each message designating whether it was pinned by author or teacher or both. 
4. Let's have them change in place. Add a search bar at the top of the current forum page. I think it would make sense to only search the posts in the selected category? But if you think otherwise lmk!
5. No particular preference haha. Go for ones that are free and open source, and I'd say to stick with the ones that are the easiest to implement/use!

Thanks for all your work you are AMAZING

**Comment by jaydenpersonnat** [comment]
Update: I just finished implementing all the functionality above, though I do have to go back and style everything. 

I think the only question I have right now on this search. Right now, I've implemented it such that searching is done `onChange`, in the sense that the results immediately show up as the user types. Do you want to go with this or only perform a search when the user clicks Submit?

**Comment by IsoPhoenix** [comment]
I generally prefer onChange! With styling you can take a look at the theming/styling Ashley has already implemented, you can talk to either of us if you have questions on using them!

Matthew Su
Harvard College Class of 2024
A.B. Candidate in Chemistry and Computer Science
